spring.application.name=HospitalMangement
spring.datasource.class-Driver-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Hospitaldb
spring.datasource.username=root
spring.datasource.password=root

server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.sql-show=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anvprasad124@gmail.com
spring.mail.password=zwmk uzya liee ojui
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

